### ISSUE TITLE
Final Sprint!!!!!!!!!!!!

### ISSUE THREAD

**Issue by lcb931023** [team-bubbles/nmcs1#29]
**Priority from highest to lowest**
- [x] #26 Page Piling
- [x] #32 Fleshing out Project Details
- [x] #30 About me Section
- [x] #18 Icons
- [x] #31 Clickable Arrow Navigation
- [ ] #16 Slideshow at the Header
- [ ] #20 Project Grid Loading
- [x] #27 Keyboard Navigation
- [ ] #28 Theme Color
- [ ] #21 Browser Testing 
- [x] #25 Get rid of Foundation

And to make this something people would want to use - 
- [ ] #15 Make template more User-friendly

It would require documentation, better modularization and instruction.
